---
- name: Install latest st2web package
  become: yes
  yum:
    name: st2web
    state: latest
  when: st2_version == "stable"
  notify:
    - Restart st2
  tags: st2web

- name: Install exact st2web package
  become: yes
  yum:
    name: st2web={{ st2_version }}-{{ st2web_revision }}
    state: present
  when: st2_version != "stable"
  notify:
    - Restart st2
  tags: st2web

- name: Create ssl cert dir
  become: yes
  file:
    state: directory
    dest: /etc/ssl/st2
  tags: st2web

- name: Create ssl cert
  become: yes
  shell: openssl req -x509 -newkey rsa:2048 -keyout /etc/ssl/st2/st2.key -out /etc/ssl/st2/st2.crt -days 365 -nodes -subj "/C=US/ST=California/L=Palo Alto/O=StackStorm/OU=Information Technology/CN=$(hostname)"
  args:
    creates: /etc/ssl/st2/st2.key
  notify:
    - Restart nginx for st2web
  tags: st2web

- name: Create nginx folders
  become: yes
  file:
    state: directory
    path: "{{ item }}"
  with_items:
    - /etc/nginx/sites-available/
    - /etc/nginx/sites-enabled/
  tags: st2web

- name: Ensure site-available is loaded
  become: yes
  lineinfile:
    state: present
    dest: /etc/nginx/nginx.conf
    regexp: 'include /etc/nginx/sites-enabled/'
    insertafter: '    include /etc/nginx/conf.d/'
    line: 'include /etc/nginx/sites-enabled/*;'
  tags: st2web

- name: Copy Nginx config
  become: yes
  command: cp /usr/share/doc/st2/conf/nginx/st2.conf /etc/nginx/sites-available/
  args:
    creates: /etc/nginx/sites-available/st2.conf
  notify:
    - Restart nginx for st2web
  tags: st2web

- name: Enable site
  become: yes
  file:
    state: link
    src: /etc/nginx/sites-available/st2.conf
    dest: /etc/nginx/sites-enabled/st2.conf
  notify:
    - Restart nginx for st2web
  tags: st2web
